### ISSUE TITLE
NGboost clf: array error

### ISSUE THREAD

**Issue by SeungukJeong** [Jina-yu/credit-now#9]
<img width="775" alt="image" src="https://user-images.githubusercontent.com/62808393/167341437-50a3c6b4-80d7-431b-84f5-9f14c6cbcb48.png">

ngboost clf 실행시 데이터셋의 타입 문제로 오류가 생김

**Comment by minyeamer** [comment]
<img width="428" alt="Screen Shot 2022-05-09 at 1 34 04 PM" src="https://user-images.githubusercontent.com/17109173/167342787-1404988c-f5c9-4778-b156-bf56f3cb45eb.png">

float형 열들을 전부 int형으로 변환해야 합니다.
train_test_split()과 encoding을 전부 적용하지 않은 원본 데이터프레임에서
numeric 열을 전부 범위로 감싸서 categorical 열로 만들고 one-hot encoding 적용하면
정상적으로 실행될 것 같습니다.

**Comment by minyeamer** [comment]
load_train_data 사용법

(1)test_size 0으로 설정 시 dataframe 반환
(2)test_size 설정 시 split된 sklearn array 반환

(1)encoding=False 설정 시 standard/one-hot 적용 안된 데이터 반환
(2)encoding=True 설정 시 standard/one-hot 적용된 데이터 반환

**Comment by SeungukJeong** [comment]
<img width="328" alt="image" src="https://user-images.githubusercontent.com/62808393/167521342-8c2c2e72-9e1a-4dac-8e9b-aa4c8face8a4.png">
변경 후 모델 적용해보기
